/*
------------------------------------------------------Changelog------------------------------------------------------
Rarities:
normal --> uncommon --> rare --> super rare --> epic --> legendary --> mythical --> godly --> EX
grey        green       blue      purple        silver       gold        red      diamond   black
 0            1          2          3             4           5           6         7        8
 x1         x1.3       x1.7       x2.2           x3          x4           x6        x9      

---------------------------------------------------------------------------------------------------------------------
*/

// Constants (catches spelling mistakes, the code will error if one of these is spelt wrong)
const N = 0;
const UC = 1;
const R = 2;
const SR = 3;
const E = 4;
const L = 5;
const M = 6;
const G = 7;
const EX = 8;

const str = 'str';
const int = 'int';
const hp = 'hp';
const mp = 'mp';

const male = 'male';
const female = 'female';

const rankN = { // N
    Abby: { // healer
        name: `Abby`,
        title: `Healer`,
        description: `Abby is a novice healer who recently joined the Adventurers Guild. She knows a few healing spells but can't fight very well, so she's suitable for the support role.`,
        personality: 'timid',
        stats: {atk: 'low', def: 'low'},
        rarity: N,
        gender: female,
        pfp: `assets/AnimeGirl2.jpeg`,
        hp: 90, 
        mp: 120, 
        str: 0.8,
        int: 100, 
        mpRegen: 30, 
        agi: 75,
        skills: ['slap', 'lesserHeal', 'mediumHeal', 'lesserAreaHeal'],
        armour: {physical: [0, 0], magic: [0, 0]}, 
        spec: mp,
    },
    Yuki: { // dps
        name: `Yuki`, // name of character
        title: `Soldier`, // title to put before name
        description: `Yuki recently graduated from the kingdom's swordmen academy. She's not inexperienced with the sword and knows how to use mana to strengthen her attacks. Additionally her light armour improves her felxibility and allows her to hit harder.`, // description of character
        personality: 'calm', // determines voice lines for character
        stats: {atk: 'high', def: 'low'}, // stats to show to user
        rarity: N, // how 'good' the character is. In ascending order, the rarities are N (normal), UC (uncommon), R (rare), SR (super rare), E (epic), L (legendary), and G (godly)
        gender: female, // gender of character, used for determining voice lines
        pfp: `assets/AnimeGirl42.jpeg`, // character icon image
        hp: 110, // health
        mp: 75, // mana
        str: 1.25, // strength (physical attack damage = attack base damage * str)
        int: 100, // intelligence (magic attack damage = attack base damage * int/100)
        mpRegen: 5, // mana regeneration per round
        skills: ['slash', 'lesserStrengthEnhancement', 'swordCharge', 'overheadStrike'], // attacks and abilities (every character should have at least 4)
        armour: {physical: [0, 0], magic: [0, 0]}, // resistances to damage, first number is flat damage reduction, second is a percentage reduction
    },
    Akane: { // tank
        name: `Akane`,
        title: `Knight`,
        description: `Akane is one of the kingdom's many knights. She's got good durability and knows her way around a fight.`,
        personality: 'arrogant',
        stats: {atk: 'medium', def: 'high'},
        rarity: N,
        gender: female,
        pfp: `assets/AnimeGirl40.jpeg`,
        hp: 170,
        mp: 30,
        str: 1,
        int: 95,
        mpRegen: 5,
        agi: 80,
        skills: ['stunningBlows', 'slash', 'reinforceArmour', 'swordCharge'],
        armour: {physical: [7, 10], magic: [2, 0]}, 
        spec: hp,
    },
    Emi: { // glass cannon magic dps
        name: `Emi`,
        title: `Mage`,
        description: `Emi is an apprentice mage from the red mage tower. She relies on her affinity with the fire element to cast powerful fire elemntal attacks.`,
        personality: 'angry',
        stats: {atk: 'high', def: 'none'},
        rarity: N,
        gender: female,
        pfp: `assets/AnimeGirl48.jpeg`,
        hp: 60, 
        mp: 150,
        str: 0.9,
        int: 100, 
        mpRegen: 25, 
        agi: 75,
        skills: ['fireball', 'fireLance', 'fireArrows', 'firestorm'],
        armour: {physical: [0, 0], magic: [0, 0]},
        spec: mp,
    },
    Henrietta: { // summoner
        name: `Henrietta`,
        title: `Spedlord`,
        description: `Henrietta le Bird is very tall. Way too tall. That is her only defining character trait.`,
        personality: 'timid',
        stats: {atk: 'low', def: 'none'},
        rarity: N,
        gender: female,
        pfp: `assets/AnimeGirl53.jpeg`,
        hp: 80,
        mp: 120,
        str: 0.75,
        int: 69,
        mpRegen: 25,
        agi: 50,
        skills: [`punch`, `summonBird`, `summonRock`, `scam2`],
        armour: {physical: [0, 0], magic: [0, 0]},
    },
    Hana: { // tank / dps
        name: `Hana`,
        title: `Wanderer`,
        description: `Hana was orphaned after her village was razed by the demon lord's army. She swore a vow of vengence to hunt down all demonic creatures and trains relentlessly every day.`,
        personality: 'angry',
        stats: {atk: 'high', def: 'medium'},
        rarity: N,
        gender: female,
        pfp: `assets/AnimeGirl8.jpeg`,
        hp: 125,
        mp: 50,
        str: 1,
        int: 100,
        mpRegen: 7,
        agi: 95,
        skills: ['slash', 'raiseGuard', 'swordCharge', 'overheadStrike'],
        armour: {physical: [5, 5], magic: [2, 0]}, 
        spec: hp,
    },
    Maiko: { // dps
        name: `Maiko`,
        title: `Wanderer`, 
        description: `With no home to call her own, Maiko roams from town to town, taking on any quest that promises a warm meal and a place to rest for the night. Years of living alone in the wilderness has taught Maiko how to fight and some basic first aid.`,
        personality: 'calm', 
        stats: {atk: 'high', def: 'low'}, 
        rarity: N,
        gender: female, 
        pfp: `assets/AnimeGirl41.jpeg`, 
        hp: 100, 
        mp: 100, 
        str: 1, 
        int: 100, 
        mpRegen: 10, 
        agi: 120,
        skills: ['heavySlash', 'lesserStrengthEnhancement', 'inferiorSwordDance', 'firstAid'], 
        armour: {physical: [2, 0], magic: [0, 0]}, 
    },
    Chika: { // no class
        name: `Chika`,
        title: `Weakling`, 
        description: `Chika became an adventurer to quickly earn some money for the treatment of her sick mother. She is inexperienced and is rather weak.`,
        personality: 'calm', 
        stats: {atk: 'medium', def: 'low'}, 
        rarity: N,
        gender: female, 
        pfp: `assets/AnimeGirl74.jpeg`, 
        hp: 100, 
        mp: 0, 
        str: 0.9, 
        int: 100, 
        mpRegen: 10, 
        agi: 75,
        skills: ['slash', 'rockThrow', 'raiseGuard'], 
        armour: {physical: [0, 0], magic: [0, 0]}, 
    },
    Reina: { // dps
        name: `Reina`,
        title: `Adventurer`, 
        description: `Reina is a self taught swordswoman and has been adventuring for some time. She is decently skilled with a sword.`,
        personality: 'calm', 
        stats: {atk: 'high', def: 'none'}, 
        rarity: N,
        gender: female, 
        pfp: `assets/AnimeGirl72.jpeg`, 
        hp: 150, 
        mp: 50, 
        str: 1.25, 
        int: 90, 
        mpRegen: 10, 
        agi: 100,
        skills: ['rapidSlash', 'thrust', 'lesserStrengthEnhancement', 'overheadStrike'], 
        armour: {physical: [0, 0], magic: [0, 0]}, 
    },
};
const rankUC = { // UC
    Rei: { // tank
        name: `Rei`,
        title: `Warrior`,
        description: `Rei is clumsy and often misses her attacks, but has a suit of heavy armour that allows her to tank damage quite well.`,
        personality: 'confident',
        stats: {atk: 'low', def: 'high'},
        rarity: UC,
        gender: female,
        pfp: `assets/AnimeGirl9.jpeg`,
        hp: 230, 
        mp: 30,
        str: 1,
        int: 80,
        mpRegen: 5,
        agi: 50,
        skills: ['kick', 'raiseGuard', 'wildSwing', 'reinforceArmour'],
        armour: {physical: [20, 25], magic: [5, 5]}, 
        spec: hp,
    },
    Ellen: { // dps
        name: `Ellen`,
        title: `Martial Artist`, 
        description: `Ellen is a low ranking diciple of the Wudang Sect. She trains hard but has no tallent so Ellen has mastered the basics but struggles with controlling qi (mana).`,
        personality: 'calm', 
        stats: {atk: 'medium', def: 'low'}, 
        rarity: UC,
        gender: female, 
        pfp: `assets/AnimeGirl62.jpeg`, 
        hp: 160, 
        mp: 40, 
        str: 1.5, 
        int: 100, 
        mpRegen: 5, 
        agi: 110,
        skills: ['heavyBlows', 'stunningBlows', 'flyingKick', 'lesserPhysicalEnhancement'], 
        armour: {physical: [5, 15], magic: [3, 0]}, 
    },
    Ally: { // magic dps
        name: `Ally`,
        title: `Mage`,
        description: `Ally is a student from the magic academy. She has grasped the fundamentals and can use basic magic attacks.`,
        personality: 'angry',
        stats: {atk: 'high', def: 'low'},
        rarity: UC,
        gender: female,
        pfp: `assets/AnimeGirl21.jpeg`,
        hp: 100, 
        mp: 160,
        str: 0.9,
        int: 110, 
        mpRegen: 60, 
        agi: 75,
        skills: ['magicArrow', 'multiMagicArrow', 'windBlade', 'fireBlast'],
        armour: {physical: [2, 5], magic: [5, 25]},
        spec: mp,
    },
    Sora: { // healer
        name: `Sora`,
        title: `Apprentice`,
        description: `Sora is a novice mage from the white mage tower. She wields light elemental magic which is used mostly for healing spells.`,
        personality: 'calm',
        stats: {atk: 'low', def: 'low'},
        rarity: UC,
        gender: female,
        pfp: `assets/AnimeGirl73.jpeg`,
        hp: 100, 
        mp: 160, 
        str: 0.9,
        int: 100, 
        mpRegen: 40, 
        agi: 75,
        skills: ['punch', 'magicArrow', 'mediumHeal', 'mediumAreaHeal'],
        armour: {physical: [2, 5], magic: [2, 5]}, 
        spec: mp,
    },
    Mio: { // crowd control dps
        name: `Mio`, 
        title: ``, 
        description: `Mio is an excellent fighter, able to effectively utilise her speed and agility to take down multiple enemies at once.`, 
        personality: 'excited', 
        stats: {atk: 'high', def: 'medium'}, 
        rarity: UC, 
        gender: female, 
        pfp: `assets/AnimeGirl77.jpeg`,
        hp: 160, 
        mp: 100, 
        str: 1.5, 
        int: 100, 
        mpRegen: 15, 
        skills: ['rapidSlash', 'mediumPhysicalEnhancement', 'manyKnifeThrow', 'minorSwordDance'], 
        armour: {physical: [8, 15], magic: [2, 0]}, 
    },
    Naomi: { // support
        name: `Naomi`,
        title: `Commander`, 
        description: `Naomi was a general from a fallen kingdom. She knows how to lead troops and her presence can boost the strength and moral of nearby allies. Why did her kingdom fall? Probably because Naomi wan't that good of a general...`,
        personality: 'confident', 
        stats: {atk: 'low', def: 'low'}, 
        rarity: UC,
        gender: female, 
        pfp: `assets/AnimeGirl75.jpeg`, 
        hp: 150, 
        mp: 110, 
        str: 1.25, 
        int: 120, 
        mpRegen: 25, 
        skills: ['punch', 'lesserCommandingPresence', 'lesserWarCry', 'rangedUnbreakableWill'], 
        armour: {physical: [0, 10], magic: [0, 10]}, 
    },
};
const rankR = { // R
    Anonymous: { // debuffer / support
        name: `Anonymous`,
        title: `Positron Lord`,
        description: `Former high school student, Anonymous135 quantum tunneled her way into the other world usilising her extensive knowledge of the standard model. She hates the demon lord with a burning passion as the demons don't obey the laws of physics`,
        personality: 'calm',
        stats: {atk: 'low', def: 'low'},
        rarity: R,
        gender: female,
        pfp: `assets/AnimeGirl54.jpeg`,
        hp: 140,
        mp: 200,
        str: 0.9,
        int: 150,
        mpRegen: 40,
        agi: 110,
        skills: [`positronRay`,`analysis`,`gravityBind`,`lecture`],
        armour: {physical: [5, 25], magic: [5, 10]},
    }, 
    Miki: { // tank / dps
        name: `Miki`,
        title: `Paladin`,
        description: `A veteran of many holy wars, Miki has fought in numerous battles against heretics and demons, emerging victorious and more resolute in her faith each time. Her unwavering devotion towards the [redacted]ism church guides her every move.`,
        personality: 'calm',
        stats: {atk: 'high', def: 'high'},
        rarity: R,
        gender: female,
        pfp: `assets/AnimeGirl57.jpeg`,
        hp: 170,
        mp: 170,
        str: 1.5,
        int: 75,
        mpRegen: 40,
        agi: 90,
        skills: ['improvedSlash', 'divineProtection', 'inferiorSwordDance', 'righteousSmite'],
        armour: {physical: [25, 30], magic: [15, 30]}, 
    }, 
    Kaede: { // tank
        name: `Kaede`,
        title: `Shielder`,
        description: `Hailing from a fallen empire, Kaede is a soldier experienced in team combat. She wields her shield effectively to protect her allies from harm.`,
        personality: 'calm',
        stats: {atk: 'low', def: 'high'},
        rarity: R,
        gender: female,
        pfp: `assets/AnimeGirl18.jpeg`,
        hp: 300, 
        mp: 50,
        str: 1,
        int: 80,
        mpRegen: 5,
        agi: 60,
        skills: ['heavyBlows', 'shieldBash', 'raiseGuard', 'reinforceShield'],
        armour: {physical: [25, 50], magic: [15, 35]}, 
    },
    Junko: { // magic dps
        name: `Junko`,
        title: `Mage`,
        description: `Junko is a young artillery mage from the red mage tower. She specializes in fire elemental attacks at long ranges but doesn't do well at close ranges.`,
        personality: 'angry',
        stats: {atk: 'high', def: 'low'},
        rarity: R,
        gender: female,
        pfp: `assets/AnimeGirl69.jpeg`,
        hp: 100, 
        mp: 240,
        str: 0.9,
        int: 150, 
        mpRegen: 60, 
        agi: 80,
        skills: ['fireLance', 'greaterFireball', 'improvedFireArrows', 'hellfire'],
        armour: {physical: [5, 10], magic: [25, 50]},
    },
    Saki: { // dps / summoner
        name: `Saki`,
        title: `Necromancer`,
        description: `Saki is a dark mage from the black mage tower. She has grasped the fundamentals of necromacy and can raise low teir undead.`,
        personality: 'calm',
        stats: {atk: 'medium', def: 'none'},
        rarity: R,
        gender: female,
        pfp: `assets/AnimeGirl76.jpeg`,
        hp: 170, 
        mp: 170,
        str: 0.75,
        int: 90, 
        mpRegen: 60, 
        agi: 75,
        skills: ['shadowBall', 'summonLowTierSkeleton', 'summonLesserDemon', 'smalldarkBlast'],
        armour: {physical: [0, 0], magic: [0, 0]},
    },
};
const rankSR = { // SR
    Lucy: { // tank
        name: `Lucy`,
        title: `The Invulnerable`,
        description: `Lucy is a timid girl who somehow stumbled upon a legendary set of equipment. She has no idea how to fight but her equipment makes her nearly invincible.`,
        personality: 'timid',
        stats: {atk: 'medium', def: 'extreme'},
        rarity: SR, 
        gender: female,
        pfp: `assets/AnimeGirl14.jpeg`,
        hp: 100, 
        mp: 100, 
        str: 2, 
        int: 75, 
        mpRegen: 25, 
        agi: 90,
        skills: ['wildSwing', 'wildCharge', 'cower', 'sparkleSlash'], 
        armour: {physical: [75, 95], magic: [50, 90]}, 
    },
    Edwinette: { // support
        name: `Edwinette`,
        title: `Drug Dealer`,
        description: `Former chemist and part time drug dealer, Edwinette broke through reality to reach the other world by synthesising a compound with negative molar mass. Now, she synthesises her drugs with alchemy and deals meth in the other world, where there are no pesky policemen to ruin her business. However, the return of the demon king has negatively affected her profits, so the demon lord must die.`,
        personality: 'angry',
        stats: {atk: 'medium', def: 'low'},
        rarity: SR,
        gender: female,
        pfp: `assets/AnimeGirl56.jpeg`,
        hp: 220,
        mp: 220,
        str: 1,
        int: 169,
        mpRegen: 50,
        skills: ['mediumMeth', 'molotovCocktail', 'greaterHeal', 'greaterMeth'],
        armour: {physical: [5, 10], magic: [5, 10]},
    },
    WSM: { // support
        name: `WSM`,
        title: `Musician`, 
        description: `Fomer high school music student, WSM played the oboe so loudly that spacetime resonated at its fundamental frequency and shattered, sending her to the other world. After her transmigration, WSM's music gained magical properties, granting buffs to the allies around her.`,
        personality: 'calm', 
        stats: {atk: 'low', def: 'low'}, 
        rarity: SR,
        gender: female, 
        pfp: `assets/AnimeGirl67.jpeg`, 
        hp: 220, 
        mp: 220, 
        str: 1, 
        int: 130, 
        mpRegen: 60, 
        skills: ['destructiveResonance', 'battleBallad', 'strengthingSong', 'healingMelody'], 
        armour: {physical: [5, 10], magic: [10, 25]}, 
    },
    Shiori: { // dps
        name: `Shiori`,
        title: `Martial Master`, 
        description: `Born and raised in the Mount Hua sect, Shiori has mastered the plum blossom sword style. Her swift and deadly sword strikes can cut down enemies with ease.`,
        personality: 'angry', 
        stats: {atk: 'high', def: 'low'}, 
        rarity: SR,
        gender: female, 
        pfp: `assets/AnimeGirl63.jpeg`, 
        hp: 250, 
        mp: 200, 
        str: 1.5, 
        int: 110, 
        mpRegen: 70, 
        agi: 150,
        skills: ['flyingKick', 'minorSwordDance', 'skySplittingSlash', 'superiorPhysicalEnhancement'], 
        armour: {physical: [15, 25], magic: [15, 30]}, 
    },
    Risa: { // magic support
        name: `Risa`,
        title: `Grand Magus`,
        description: `Risa is a powerful mage from the purple mage tower. She can adeptly weilds gravity magic in a vareity of combat situations.`,
        personality: 'confident',
        stats: {atk: 'medium', def: 'low'},
        rarity: SR,
        gender: female,
        pfp: `assets/AnimeGirl71.jpeg`,
        hp: 140, 
        mp: 300,
        str: 0.9,
        int: 200, 
        mpRegen: 90, 
        agi: 90,
        skills: ['crushingGravity', 'strengthMagic', 'gravityBind', 'wideCrushingGravity'],
        armour: {physical: [5, 10], magic: [25, 50]},
    },
    Tomoe: { // tank
        name: `Tomoe`,
        title: `Shielder`,
        description: `Tomoe is a high ranking adventurer from the adventurer's guild. She was experienced many battles and is always ready to protect her teammates.`,
        personality: 'confident',
        stats: {atk: 'low', def: 'high'},
        rarity: SR,
        gender: female,
        pfp: `assets/AnimeGirl16.jpeg`,
        hp: 400, 
        mp: 40,
        str: 1.25,
        int: 80,
        mpRegen: 25,
        agi: 60,
        skills: ['heavyBlows', 'improvedShieldBash', 'reinforceShield', 'greaterReinforceArmour'],
        armour: {physical: [40, 75], magic: [30, 50]}, 
    },
};
const rankE = { // E
    Pi_thagoreas: { // summoner
        name: `π-thagoreas`,
        title: `Chicken Farmer`,
        description: `Born and raised on on a rural farm, π-thagoreas grew up as a talented chicken farmer, ruling over several nations (chicken pens) and over 300 loyal subjects (chickens). When the demon lord attacked, π-thagoreas was driven out of her hometown, her chicken pens destroyed. Swearing revenge against the evil demons, π-thagoreas is willing to do anything to kill the demon lord.`,
        personality: 'calm',
        stats: {atk: 'none', def: 'low'},
        rarity: E,
        gender: female,
        pfp: `assets/AnimeGirl52.jpeg`,
        hp: 300,
        mp: 300,
        str: 2,
        int: 120,
        mpRegen: 50,
        skills: [`pitchfork`, `healingHerbs`, `summonRooster`, `summonFlock`, `summonPheonix`],
        armour: {physical: [10, 10], magic: [5, 10]},
        spec: mp,
    },
    Zoe: { // dps
        name: `Zoe`,
        title: `Reaper`, 
        description: `Zoe is an elusive individual. Little is known about her and the reapers, apart from them possessing otherworldly physical strength and magical abilities.`,
        personality: 'calm', 
        stats: {atk: 'high', def: 'medium'}, 
        rarity: E,
        gender: female, 
        pfp: `assets/AnimeGirl19.jpeg`, 
        hp: 280, 
        mp: 340, 
        str: 1.5, 
        int: 125, 
        mpRegen: 120, 
        agi: 175,
        skills: ['savageTornado', 'darkBlast', 'superiorBodyEnhancement', 'ultraHeavySlash', 'minorSoulHarvest'], 
        armour: {physical: [35, 50], magic: [30, 75]}, 
    },
    Nagi: { // dps / support
        name: `Nagi`,
        title: `Princess`, 
        description: `Nagi is a warrior princess from the Toomwn kingdom. She frequently leads her army into battle and is an experienced commander and warrior.`,
        personality: 'calm', 
        stats: {atk: 'high', def: 'medium'}, 
        rarity: E,
        gender: female, 
        pfp: `assets/AnimeGirl65.jpeg`, 
        hp: 200, 
        mp: 400, 
        str: 1.5, 
        int: 160, 
        mpRegen: 100, 
        agi: 160,
        skills: ['improvedThrust', 'commandingPresence', 'rallyingSpeech', 'lesserSwordDance'], 
        armour: {physical: [25, 40], magic: [15, 25]}, 
    },
    Izumi: { // tank
        name: `Izumi`,
        title: `Guardian`,
        description: `Izumi has faithfully guarded the gates of Fort Spud for many years. She can wield her spear and shield effectively to attack and defend.`,
        personality: 'confident',
        stats: {atk: 'medium', def: 'high'},
        rarity: E, 
        gender: female,
        pfp: `assets/AnimeGirl17.jpeg`,
        hp: 500, 
        mp: 100, 
        str: 1.25, 
        int: 75, 
        mpRegen: 30, 
        agi: 80,
        skills: ['improvedThrust', 'mediumRaiseGuard', 'greaterReinforceShield', 'improvedCharge'], 
        armour: {physical: [90, 80], magic: [75, 75]}, 
        spec: hp,
    },
    Agent420: { // dps
        name: `Agent-420`,
        title: ``,
        description: `A special operative of the [redacted]ism chruch, Agent-420 is skilled in the arts of infiltration and assasination.`,
        personality: 'calm',
        stats: {atk: 'extreme', def: 'none'},
        rarity: E,
        gender: female,
        pfp: `assets/AnimeGirl30.jpeg`,
        hp: 100,
        mp: 500,
        str: 1.5,
        int: 140,
        mpRegen: 25,
        skills: [`dagger`, `assaultRifle`, `fragGrenade`, `evasiveManoeuvers`, `sniperRifle`],
        armour: {physical: [0, 0], magic: [0, 0]},
        spec: mp,
    },
    Agent069: { // dps
        name: `Agent-069`,
        title: ``,
        description: `A special operative of the [redacted]ism chruch, Agent-069 is skilled in the arts of infiltration and assasination.`,
        personality: 'calm',
        stats: {atk: 'extreme', def: 'none'},
        rarity: E,
        gender: female,
        pfp: `assets/AnimeGirl31.jpeg`,
        hp: 100,
        mp: 500,
        str: 1.5,
        int: 140,
        mpRegen: 25,
        skills: [`dagger`, `assaultRifle`, `fragGrenade`, `evasiveManoeuvers`, `sniperRifle`],
        armour: {physical: [0, 0], magic: [0, 0]},
        spec: mp,
    },
};
const rankL = { // L
    Kohana: { // dps / support
        name: `Kohana`,
        title: `Archmage`,
        description: `Kohana is a grand archmage who has seen countless battles over the centuries. She weilds high teir shadow magic.`,
        personality: 'confident',
        stats: {atk: 'high', def: 'low'},
        rarity: L,
        gender: female,
        pfp: `assets/AnimeGirl27.jpeg`,
        hp: 250,
        mp: 550,
        str: 1.2,
        int: 300,
        mpRegen: 120,
        agi: 150,
        skills: ['shadowLance', 'forceLance', 'darkBlast', 'arcaneBlast', 'gravityBind', 'mediumHeal'],
        armour: {physical: [15, 20], magic: [25, 75]},
    },
    Misato: { // healer
        name: `Misato`,
        title: `High Priestess`,
        description: `Misato is a high priestess of the [redacted]ism church. She wields powerful divine and healing magic.`,
        personality: 'confident',
        stats: {atk: 'low', def: 'low'},
        rarity: L,
        gender: female,
        pfp: `assets/AnimeGirl5.jpeg`,
        hp: 350,
        mp: 450,
        str: 1,
        int: 80,
        mpRegen: 120,
        skills: ['greaterHeal', 'greaterAreaHeal', 'superiorHeal', 'healAura', 'righteousFury', 'righteousSmite'],
        armour: {physical: [15, 10], magic: [15, 25]},
        spec: mp,
    },
    HKW: { // dps / support
        name: `HKW`,
        title: `Hunter Killer`,
        description: `HKW is a skilled asassin who has hunted down countless important individuals.`,
        personality: 'confident',
        stats: {atk: 'high', def: 'low'},
        rarity: L,
        gender: female,
        pfp: `assets/AnimeGirl28.jpeg`,
        hp: 300,
        mp: 500,
        str: 2,
        int: 200,
        mpRegen: 100,
        skills: ['dagger', 'poisonPowder', 'ultraHeavySlash', 'improvedFirstAid', 'magicSealingSword', 'superiorBodyEnhancement'],
        armour: {physical: [25, 25], magic: [25, 25]},
    },
};
const rankM = { // M
    Misaki: { // dps
        name: `Misaki`,
        title: `Swordmaster`,
        description: `Misaki is a powerful swordmaster who wields a pair of deadly blades. She is also the first diciple of the sword goddess Natsuki.`,
        personality: 'confident',
        stats: {atk: 'high', def: 'medium'},
        rarity: M,
        gender: female,
        pfp: `assets/AnimeGirl58.jpeg`,
        hp: 500, 
        mp: 700,
        str: 3,
        int: 130,
        mpRegen: 175,
        agi: 180,
        skills: ['ascendedSlash', 'ascendedThrust', 'ascendedOverheadStrike', 'auraSlash', 'swordDance', 'battleFocus'],
        armour: {physical: [80, 75], magic: [60, 75]}, 
        additionalAp: 1,
    },
    Saori: { // tank dps
        name: `Saori`,
        title: `Dragonslayer`,
        description: `Saori is a skilled warrior who has slain many evil dragons and protected the continent multiple times.`,
        personality: 'confident',
        stats: {atk: 'high', def: 'high'},
        rarity: M,
        gender: female,
        pfp: `assets/AnimeGirl64.jpeg`,
        hp: 600, 
        mp: 600,
        str: 2.5,
        int: 120,
        mpRegen: 150,
        agi: 150,
        skills: ['rapidStrikes', 'mediumRaiseGuard', 'auraSlash', 'ultraHeavySlash', 'lesserSwordDance', 'battleFocus'],
        armour: {physical: [100, 80], magic: [75, 80]}, 
        additionalAp: 1,
    },
    JLee: { // tank
        name: `JLee`,
        title: `Anime Protagonist`,
        description: `JLee is the very definition of a protagonist. Her powerful plot armour shields her from attacks, while the power of friendship strengthens her devastating blows.`,
        personality: 'confident',
        stats: {atk: 'medium', def: 'high'},
        rarity: M,
        gender: female,
        pfp: `assets/AnimeGirl80.jpeg`,
        hp: 800, 
        mp: 400,
        str: 1.5,
        int: 200,
        mpRegen: 50,
        agi: 125,
        skills: ['rapidStrikes', 'pervertedStare', 'mediumRaiseGuard', 'energyBlast', 'unbreakableWill', 'instantRecovery'],
        armour: {physical: [150, 80], magic: [150, 80]}, 
        additionalAp: 1,
    },
};
const rankG = { // G
    Natsuki: { // glass cannon dps
        name: `Natsuki`,
        title: `Sword Goddess`,
        description: `Natsuki, the Sword Goddess, is an unparalleled master of swordsmanship. Her strikes are swift and devastating, but her frail body cannot withstand much damage.`,
        personality: 'calm',
        stats: {atk: 'extreme', def: 'low'},
        rarity: G,
        gender: female,
        pfp: `assets/AnimeGirl10.jpeg`,
        hp: 300,
        mp: 1500,
        str: 6,
        int: 250,
        mpRegen: 400,
        agi: 250,
        skills: ['ascendedSlash', 'ascendedThrust', 'auraSlash', 'magicSealingSword', 'swordDance', 'realitySlash', 'superCharge'],
        armour: {physical: [100, 0], magic: [50, 0]},
        additionalAp: 1,
        spec: mp,
    },
    Yui: { // tank / support
        name: `Yui`,
        title: `War Goddess`,
        description: `Yui, the War Goddess, commands the battlefield with an iron fist. Her presence alone can turn the tide of battle, and her unparalleled strength and defense make her a formidable opponent.`,
        personality: 'arrogant',
        stats: {atk: 'medium', def: 'high'},
        rarity: G,
        gender: female,
        pfp: `assets/AnimeGirl38.jpeg`,
        hp: 1450,
        mp: 350,
        str: 1.75,
        int: 200,
        mpRegen: 200,
        agi: 175,
        skills: ['ascendedSlash', 'sevenfoldSlash', 'warCry', 'battlefieldCommand', 'improvedSavageTornado', 'righteousSmite', 'unbreakableWill'],
        armour: {physical: [200, 90], magic: [175, 85]},
        additionalAp: 1,
        spec: hp,
    },
    Prawns: { // healer
        name: `Prawns`,
        title: `Surgeon`,
        description: `Prawns became a master surgeon with her perfect scores in her med exams. She can masterfully complete the most difficult opperations with 102% success rate. Because Prawns was simply too good, the godess transmigrated her to the other world where her healing would be more useful. Beware, Borude does not regenerate mana naturally, she can only gain more mana from skills or external buffs.`,
        personality: 'confident',
        stats: {atk: 'low', def: 'low'},
        rarity: G,
        gender: female,
        pfp: `assets/AnimeGirl61.jpeg`,
        hp: 1000,
        mp: 800,
        str: 1,
        int: 4200,
        mpRegen: 0,
        skills: ['organHarvest', 'steroids', 'cyborgSurgery', 'bloodTransfusion', 'largeBloodTransfusion', 'heartTransplant', 'defibrillator'],
        armour: {physical: [50, 25], magic: [75, 25]},
        additionalAp: 1,
    },
};
const rankEX = { // EX
    Eco: { // useless trash
        name: `Eco`,
        title: `Hero`,
        description: `Once a high school student with big dreams and no talent, Eco got isekaied into a fantasy world where he's supposed to defeat the terrorist lord. Unfortunately, he's clumsy, weak, and perpetually out of shape. Eco plans to assemble a harem of powerful girls to do the fighting for him while he desperately tries to unlock the mysterious power sealed in his right eye, which he believes is totally awesome but actually does nothing.`,
        personality: 'chunni',
        stats: {atk: 'low', def: 'none'},
        rarity: EX,
        gender: male,
        pfp: `assets/FatEdgyGuy.jpeg`,
        hp: 60,
        mp: 25,
        str: 0.5,
        int: -1,
        mpRegen: 5,
        agi: 50,
        skills: ['punch', 'bodySlam', 'pervertedStare', 'brag'],
        armour: {physical: [0, 0], magic: [0, 0]},
        additionalAp: 1,
    },
    Eric: { // useless trash 2
        name: `Eric`,
        title: `MLG`,
        description: `Eco's only 'friend' and bad influence who is still stuck 5 years in the past. Eric is simply a cringe individual, however has potential, unlike Eco.`,
        personality: 'chunni',
        stats: {atk: 'low', def: 'none'},
        rarity: EX,
        gender: male,
        pfp: `assets/aPerson.png`,
        hp: 75,
        mp: 25,
        str: 1,
        int: -1,
        mpRegen: 5,
        agi: 50,
        skills: ['punch', 'flyingKick', 'stunningBlows', 'brag'],
        armour: {physical: [0, 0], magic: [0, 0]},
        additionalAp: 1,
    },
    Redacted: { // tank / dps
        name: `[Redacted]`,
        title: `Terrorist`,
        description: `Former high school student, [Redacted] was isekaied into the other world as the demon lord. Despite being gender bent, she is still obsessed with terrorism and decided to become the terrorist lord, who rules over many mafias and cartels, the lord of the criminal underworld. During her misadventures, [Redacted] unwillingly became the [redacted]ism cult's object of worship, which later developed into a fully fledged religion as well as designed both versions of the ==[JAT]== MQ69-Reaper attack drones. [Redacted] is also the leader of the reapers.`,
        personality: 'chunni',
        stats: {atk: 'extreme', def: 'extreme'},
        rarity: EX,
        gender: female,
        pfp: `assets/AnimeGirl51.jpeg`,
        hp: 975,
        mp: 1625,
        str: 2,
        int: 120,
        mpRegen: 200,
        agi: 125,
        skills: ['assaultRifle', 'fragGrenade', 'greaterRaiseGuard', 'swordDance', 'ultraHeavySlash', 'soulHarvest'],
        armour: {physical: [100, 80], magic: [250, 25]},
        additionalAp: 1,
    },
    Yape: { // dps / tank / support (can do anything really)
        name: `Yape`,
        title: `Mathmatician`,
        description: `Yape is the greatest mathmatician who has ever lived. She can manipulate reality with calculus equations. Yape also enjoys badminton.`,
        personality: 'confident',
        stats: {atk: 'extreme', def: 'extreme'},
        rarity: EX,
        gender: female,
        pfp: `assets/AnimeGirl79.jpeg`,
        hp: 600,
        mp: 1200,
        str: 1.5,
        int: 6900,
        mpRegen: 100,
        skills: ['badmintonSmash', 'indefiniteIntegral', 'footwork', 'fundamentalTheormOfCalculus', 'differentiate', 'mathLecture'],
        armour: {physical: [50, 50], magic: [75, 50]},
        additionalAp: 1,
    },
    MQ69Reaper: { // dps
        name: `MQ69Reaper`,
        title: `==[JAT]==`,
        description: `<span class="noWrap">==[JAT]==</span> MQ69-Reaper MK1 is the first autonomous combat vehicle designed by the [redacted]ism church to spread freedom and democracy throughout the continent of Arcadia. Piloted by the sapient ai codenamed Territory Annihilation Junkie, the MQ69-Reaper drone is a formidable foe on any battlefield, its gattling railguns and rocket pods able to tear through enemy formations with ease.`,
        personality: 'calm',
        stats: {atk: 'extreme', def: 'high'},
        rarity: EX,
        gender: female,
        pfp: `assets/MQ69-Reaper.jpeg`,
        hp: 350,
        mp: 400,
        str: 1,
        int: 690,
        mpRegen: 400,
        skills: ['ionCannon', 'gattlingRailgun', 'heavyRailcannon', 'rocketStorm', 'airStrike'],
        armour: {physical: [100, 0], magic: [75, 0]},
        additionalAp: 9999999, // unique ability: can attack as many times as mp permits
    },
    MQ69Reaper2: { // dps
        name: `MQ69Reaper2`,
        title: `==[JAT]==`,
        description: `With the success of the MQ69-Reaper MK1 drone, the [redacted]ism church designed an even stronger combat vehicle with improved armour and a larger power core. The <span class="noWrap">==[JAT]==</span> MQ69-Reaper MK2 is a second generation advanced autonomous combat vehicle designed by the [redacted]ism church to spread freedom and democracy throughout the continent of Arcadia. Piloted by the sapient ai codenamed Territory Annihilation Junkie, the MQ69-Reaper 2 drone is a formidable foe on any battlefield, its gattling railguns and rocket pods able to tear through enemy formations with ease.`,
        personality: 'calm',
        stats: {atk: 'extreme', def: 'high'},
        rarity: EX,
        gender: female,
        pfp: `assets/MQ69-Reaper2.jpeg`,
        hp: 650,
        mp: 650,
        str: 1,
        int: 690,
        mpRegen: 650,
        skills: ['ionCannon', 'gattlingRailgun', 'heavyRailcannon', 'rocketStorm', 'airStrike'],
        armour: {physical: [150, 0], magic: [125, 0]},
        additionalAp: 9999999, // unique ability: can attack as many times as mp permits
    },
};
const gachaGameEnemies = {
    goblin: { // 4 tiers
        type: 'goblin',
        enemyType: `goblinGrunt`,
        name: `Goblin`, 
        rarity: N,
        pfp: `assets/Goblin1.jpeg`,
        hp: [40, 45, 55, 75],
        mp: [0, 0, 0, 0],
        str: [0.9, 1, 1.25, 1.75],
        int: [0, 0, 0, 0],
        mpRegen: [0, 0, 0, 0],
        agi: 150,
        skills: ['hit', 'rapidHit'],
        armour: {physical: [0, 0], magic: [0, 0]},
        ai: `rng`,
    },
    goblinArcher: { // 3 tiers
        type: 'goblin',
        enemyType: `goblinArcher`,
        name: `Goblin Archer`,
        rarity: N,
        pfp: `assets/Goblin2.jpeg`,
        hp: [25, 30, 45],
        mp: [0, 0, 0],
        str: [1, 1.75, 2.5],
        int: [0, 0, 0],
        mpRegen: [0, 0, 0],
        skills: ['crossbow', 'crossbow', 'crossbowCrit'],
        armour: {physical: [2, 0], magic: [3, 0]},
        ai: `rng`,
    },
    goblinWarrior: { // 3 tiers
        type: 'goblin',
        enemyType: `goblinWarrior`,
        name: `Goblin Warrior`,
        rarity: N,
        pfp: `assets/Goblin3.jpeg`,
        hp: [75, 100, 140],
        mp: [0, 0, 0],
        str: [1.5, 1.75, 2],
        int: [0, 0, 0],
        mpRegen: [0, 0, 0],
        skills: ['smash', 'hit', 'heavySlash'],
        armour: {physical: [5, 0], magic: [3, 0]},
        ai: `rng`,
    },
    goblinGuard: { // 2 tiers
        type: 'goblin',
        enemyType: `goblinGuard`,
        name: `Goblin Guard`,
        rarity: N,
        pfp: `assets/Goblin4.jpeg`,
        hp: [150, 225],
        mp: [0, 0],
        str: [2, 2.5],
        int: [0, 0],
        mpRegen: [0, 0],
        agi: 90,
        skills: ['crushingBlow', 'heavySlash', 'roar'],
        armour: {physical: [10, 25], magic: [5, 10]},
        ai: `rng`,
    },
    goblinLord: { // boss
        type: 'goblin',
        enemyType: `goblinBoss`,
        name: `Goblin Lord`,
        rarity: N,
        pfp: `assets/Goblin5.jpeg`,
        hp: [750],
        mp: [50],
        str: [3],
        int: [0],
        mpRegen: [50],
        agi: 75,
        skills: ['crushingBlow', 'heavySlash', 'rallyingCall'],
        armour: {physical: [10, 25], magic: [5, 10]},
        ai: `rng`,
    },
    sir: { // boss
        enemyType: `sir`,
        name: `Sir`, // a certain computer science teacher
        rarity: L,
        pfp: `assets/empty.jpeg`,
        hp: 10000,
        mp: 0,
        str: 1,
        int: 100,
        mpRegen: 0,
        skills: [], // give time freeze and health increase
        armour: {physical: [50, 0], magic: [50, 0]},
        ai: `rng`,
    },
    greenDragon: { // 3 tiers
        type: 'dragon',
        enemyType: `dragonGreen`,
        name: `Green Dragon`, // (deez nuts)
        rarity: UC,
        pfp: `assets/greenDragon.jpeg`,
        hp: [500, 750],
        mp: [200, 300],
        str: [2, 3],
        int: [120, 140],
        mpRegen: [40, 60],
        agi: 75,
        skills: ['dragonClaw', 'tailSwipe', 'dragonRoar', 'dragonWing'],
        armour: {physical: [25, 50], magic: [15, 50]},
        ai: `rng`,
    },
    crystalDragon: { // 1 tier
        type: 'dragon',
        enemyType: `dragonRainbow`,
        name: `Crystal Dragon`, 
        rarity: SR,
        pfp: `assets/crystalDragon.jpeg`,
        hp: [1200],
        mp: [250],
        str: [4],
        int: [110],
        mpRegen: [50],
        agi: 125,
        skills: ['dragonClaw', 'spectralBlast', 'dragonRoar', 'earthquake'],
        armour: {physical: [50, 50], magic: [10, 0]},
        ai: `rng`,
    },
    redDragon: { // 1 tier
        type: 'dragon',
        enemyType: `dragonRed`,
        name: `Red Dragon`,
        rarity: M,
        pfp: `assets/redDragon.jpeg`,
        hp: [2500],
        mp: [1000],
        str: [4],
        int: [100],
        mpRegen: [150],
        agi: 75,
        skills: ['fireBreath', 'dragonRoar', 'infernoBeam', 'dragonBite'],
        armour: {physical: [150, 75], magic: [90, 60]},
        ai: `rng`,
    },
    electroDragon: { // 1 tier
        type: 'dragon',
        enemyType: `dragonBlue`,
        name: `Electro Dragon`,
        rarity: R,
        pfp: `assets/electroDragon.jpeg`,
        hp: [1000],
        mp: [600],
        str: [3],
        int: [200],
        mpRegen: [150],
        agi: 110,
        skills: ['dragonClaw', 'dragonWing', 'energybeam', 'lightningStrike', 'stasisField'],
        armour: {physical: [25, 25], magic: [60, 80]},
        ai: `rng`,
    },
    blackDragon: { // 1 tier
        type: 'dragon',
        enemyType: `dragonBlack`,
        name: `Black Dragon`, 
        rarity: EX, 
        pfp: `assets/blackDragon.jpeg`,
        hp: [3000],
        mp: [1000],
        str: [4],
        int: [600],
        mpRegen: [200],
        agi: 150,
        skills: ['infernoBeam', 'dragonBite', 'darkBlast', 'dimensionRedution'],
        armour: {physical: [600, 90], magic: [500, 90]},
        ai: `rng`,
        additionalAp: 1,
    },
    redDragonKing: { // 1 tier
        type: 'dragon',
        enemyType: `dragonRedBig`,
        name: `Red Dragon King`,
        rarity: M,
        pfp: `assets/redDragonKing.jpeg`,
        hp: [7500],
        mp: [2000],
        str: [8],
        int: [150],
        mpRegen: [400],
        agi: 75,
        skills: ['dragonClaw', 'fireBreath', 'infernoBeam'],
        armour: {physical: [200, 75], magic: [100, 75]},
        ai: `rng`,
    },
    chickenWeaker: { // 1 tier
        type: 'chicken',
        enemyType: `chicken`, 
        name: `Medium Chimkin`, 
        rarity: E,
        pfp: `assets/summon2.jpeg`,
        hp: [500],
        mp: [1000],
        str: [0.25],
        int: [100],
        mpRegen: [1000],
        agi: 200,
        skills: ['realitySlash', 'lightningStrike', 'infernoBeam'],
        armour: {physical: [10, 25], magic: [10, 25]},
        ai: `rng`,
    },
    chicken: { // 1 tier
        type: 'chicken',
        enemyType: `chicken`, 
        name: `Greater Chimkin`, 
        rarity: G,
        pfp: `assets/summon2.jpeg`,
        hp: [1000],
        mp: [2500],
        str: [0.5],
        int: [100],
        mpRegen: [1000],
        agi: 200,
        skills: ['realitySlash', 'lightningStrike', 'infernoBeam', 'reposition'],
        armour: {physical: [10, 25], magic: [10, 25]},
        ai: `rng`,
        additionalAp: 1,
    },
    stronkChicken: { // 1 tier
        type: 'chicken',
        enemyType: `chickenStrong`, 
        name: `SuperiorChimkin`, 
        rarity: G,
        pfp: `assets/summon2.jpeg`,
        hp: [10000],
        mp: [5000],
        str: [1],
        int: [200],
        mpRegen: [3000],
        agi: 200,
        skills: ['realitySlash', 'lightningStrike', 'infernoBeam', 'reposition'],
        armour: {physical: [100, 50], magic: [100, 50]},
        ai: `rng`,
        additionalAp: 2,
    },
    moreStronkChicken: { // 1 tier
        type: 'chicken',
        enemyType: `chickenStronger`, 
        name: `LegendaryChimkin`, 
        rarity: G,
        pfp: `assets/summon2.jpeg`,
        hp: [25000],
        mp: [6000],
        str: [1.5],
        int: [300],
        mpRegen: [4000],
        agi: 200,
        skills: ['realitySlash', 'lightningStrike', 'infernoBeam', 'reposition'],
        armour: {physical: [150, 60], magic: [150, 60]},
        ai: `rng`,
        additionalAp: 3,
    },
    veryStronkChicken: { // 1 tier
        type: 'chicken',
        enemyType: `chickenVeryStrong`, 
        name: `AscendedChimkin`, 
        rarity: G,
        pfp: `assets/summon2.jpeg`,
        hp: [50000],
        mp: [7500],
        str: [2],
        int: [400],
        mpRegen: [5000],
        agi: 200,
        skills: ['realitySlash', 'lightningStrike', 'infernoBeam', 'reposition'],
        armour: {physical: [200, 75], magic: [200, 75]},
        ai: `rng`,
        additionalAp: 4,
    },
    stronkestChicken: { // 1 tier
        type: 'chicken',
        enemyType: `chickenStrongest`, 
        name: `AscendedChimkin`, 
        rarity: EX,
        pfp: `assets/summon2.jpeg`,
        hp: [250000],
        mp: [10000],
        str: [2],
        int: [400],
        mpRegen: [5000],
        agi: 200,
        skills: ['realitySlash', 'lightningStrike', 'infernoBeam', 'reposition'],
        armour: {physical: [200, 75], magic: [200, 75]},
        ai: `rng`,
        additionalAp: 5,
    },
    shadowBat: { // 4 tiers
        type: 'dark',
        enemyType: `shadowBat`,
        name: `Ghost Bat`, // inside joke, don't question it
        rarity: N,
        pfp: `assets/shadowBat.jpeg`,
        hp: [5, 10, 15, 25],
        mp: [75, 75, 75, 75],
        str: [0.5, 0.5, 0.5, 0.5],
        int: [10, 25, 40, 50],
        mpRegen: [75, 75, 75, 75],
        agi: 200,
        skills: ['shadowBall', 'shadowLance', 'strengthInNumbers'],
        armour: {physical: [0, 95], magic: [0, 10]},
        ai: `rng`,
    },
    spider: { // 2 tiers
        type: 'bug',
        enemyType: `spider`,
        name: `Spooder`, 
        rarity: N,
        pfp: `assets/spider.jpeg`,
        hp: [30, 50],
        mp: [25, 25],
        str: [0.75, 1],
        int: [10, 10],
        mpRegen: [25, 25],
        agi: 200,
        skills: ['poisonedBite', 'web'],
        armour: {physical: [5, 10], magic: [10, 25]},
        ai: `rng`,
    },
    scorpion: { // 2 tiers
        type: 'bug',
        enemyType: `scorpion`,
        name: `Scorpion`, 
        rarity: UC,
        pfp: `assets/scorpion.jpeg`,
        hp: [150, 150],
        mp: [25, 25],
        str: [1, 1.25],
        int: [10, 10],
        mpRegen: [25, 25],
        agi: 150,
        skills: ['scorpionClaw', 'scorpionClaw', 'scorpionSting'],
        armour: {physical: [5, 10], magic: [10, 25]},
        ai: `rng`,
    },
    snake: { // 1 tier
        type: 'snake',
        enemyType: `snake`,
        name: `Snek`, 
        rarity: UC,
        pfp: `assets/snake.jpeg`,
        hp: [200],
        mp: [25],
        str: [1.5],
        int: [10],
        mpRegen: [25],
        agi: 150,
        skills: ['hiss', 'poisonedBite', 'reposition'],
        armour: {physical: [25, 25], magic: [0, 0]},
        ai: `rng`,
        additionalAp: 1,
    },
    scrapBotMelee: { // 1 tier
        type: 'robot',
        enemyType: `scrapBotMelee`,
        name: `Scrap Bot`, 
        rarity: N,
        pfp: `assets/scrapBotMelee.jpeg`,
        hp: [50],
        mp: [0],
        str: [1],
        int: [100],
        mpRegen: [0],
        agi: 200,
        skills: ['claw', 'charge'], 
        armour: {physical: [5, 10], magic: [0, 10]},
        ai: `rng`,
    },
    scrapBotRanged: { // 1 tier
        type: 'robot',
        enemyType: `scrapBotRanged`,
        name: `Scrap Bot`, 
        rarity: N,
        pfp: `assets/scrapBotRanged.jpeg`,
        hp: [30],
        mp: [0],
        str: [1],
        int: [100],
        mpRegen: [0],
        skills: ['pistol', 'miniFlamethrower'], 
        armour: {physical: [0, 10], magic: [0, 10]},
        ai: `rng`,
    },
    macelineGuard: { // 2 tiers
        type: 'robot',
        enemyType: `macelineGuard`,
        name: `Bodyguard`, 
        rarity: UC,
        pfp: `assets/bodyguard.jpeg`,
        hp: [600, 1000],
        mp: [0, 0],
        str: [1, 1.5],
        int: [100, 100],
        mpRegen: [0, 0],
        skills: ['crushingBlow', 'reposition', 'exist', 'baseballBat'], 
        armour: {physical: [25, 50], magic: [0, 50]},
        ai: `rng`,
    },
    securityDrone: { // 1 tier
        type: 'robot',
        enemyType: `securityDrone`,
        name: `Security Drone`, 
        rarity: R,
        pfp: `assets/securityDrone.jpeg`,
        hp: [250],
        mp: [150],
        str: [1],
        int: [100],
        mpRegen: [150],
        skills: ['laserBeam', 'chaingun', 'alarm', 'requestBackup'], 
        armour: {physical: [15, 10], magic: [0, 10]},
        ai: `rng`,
    },
    macelineWorker: { // 3 tiers
        type: 'robot',
        enemyType: `macelineWorker`,
        name: `Worker`, 
        rarity: R,
        pfp: `assets/workerRobot.jpeg`,
        hp: [300, 500, 750],
        mp: [0, 0, 0],
        str: [2, 3, 4],
        int: [100, 100, 100],
        mpRegen: [0, 0, 0],
        skills: ['rapidHammering', 'powerFist', 'overclock'], 
        armour: {physical: [20, 25], magic: [10, 25]},
        ai: `rng`,
    },
    securityMech: { // 2 tiers
        type: 'robot',
        enemyType: `securityMech`,
        name: `Guard Mech`, 
        rarity: SR,
        pfp: `assets/securityMech.jpeg`,
        hp: [2000, 3000],
        mp: [1000, 1500],
        str: [3, 4],
        int: [100, 100],
        mpRegen: [1000, 1500],
        skills: ['smallGattlingRailgun', 'heavyFlamethrower', 'rocketBarrage', 'powerFist'], 
        armour: {physical: [75, 50], magic: [50, 50]},
        ai: `rng`,
    },
    assembler: { // 1 tier
        type: 'robot',
        enemyType: `assemblingMachine`, // factorio moment
        name: `Assembler`, 
        rarity: R,
        pfp: `assets/assembler.png`,
        hp: [400],
        mp: [150],
        str: [1],
        int: [100],
        mpRegen: [150],
        skills: ['naniteSwarm', 'weld', 'scrapbotAssemby', 'droneAssemby'], 
        armour: {physical: [10, 10], magic: [10, 10]},
        ai: `rng`,
    },
    mace: { // boss
        enemyType: `mace`,
        name: `Mace`, 
        rarity: EX,
        pfp: `assets/AnimeGirl78.jpeg`,
        hp: [2000],
        mp: [2000],
        str: [5],
        int: [420],
        mpRegen: [2000],
        agi: 75,
        skills: ['scam3', 'stasisField', 'buildMech', 'chainLightning', 'requestBackup', 'alarm', 'ionCannon'],
        armour: {physical: [200, 90], magic: [200, 90]},
        ai: `rng`,
        additionalAp: 1,
    },
    choyu: { // boss
        enemyType: `choyu`,
        name: `Choyu`, 
        rarity: EX,
        pfp: `assets/choyu.png`,
        hp: [100000000],
        mp: [100000000],
        str: [10],
        int: [500],
        mpRegen: [10000000],
        agi: 200,
        skills: ['gigaInferno', 'godray', 'lightningStorm', 'recovery'],
        armour: {physical: [0, 0], magic: [0, 0]},
        ai: `rng`,
        additionalAp: 4,
    },
    terrorist: { // 4 tiers
        enemyType: `terrorist`,
        name: `Terrorist`, 
        rarity: UC,
        pfp: `assets/soldier1.jpeg`,
        hp: [100, 150, 200, 300],
        mp: [100, 100, 100, 100],
        str: [1, 1, 1, 1],
        int: [100, 100, 100, 100],
        mpRegen: [100, 100, 100, 100],
        skills: ['assaultRifleStandard', 'molotovCocktail', 'smallLaserBeam'], 
        armour: {physical: [10, 20], magic: [0, 10]},
        ai: `rng`,
    },
    bomber: { // 1 tier
        enemyType: `bomber`,
        name: `Bomber`, 
        rarity: UC,
        pfp: `assets/bomber.jpeg`,
        hp: [100],
        mp: [100],
        str: [1, 1],
        int: [100, 100],
        mpRegen: [100, 100],
        skills: ['grenade'], 
        armour: {physical: [5, 10], magic: [0, 10]},
        ai: `rng`,
    },
    terroristRobot: { // 1 tier
        type: `robot`,
        enemyType: `terroristRobot`,
        name: `MurderBot3000`, 
        rarity: SR,
        pfp: `assets/soldier2.jpeg`,
        hp: [500],
        mp: [300],
        str: [1, 1],
        int: [100, 100],
        mpRegen: [100, 100],
        skills: ['smallLaserBarrage'], 
        armour: {physical: [25, 25], magic: [10, 10]},
        ai: `rng`,
    },
    reaperDrone: { // boss
        enemyType: `reaperDrone`,
        name: `MQ69Reaper`, 
        rarity: EX,
        pfp: `assets/MQ69-Reaper.jpeg`,
        hp: [250],
        mp: [650],
        str: [1],
        int: [690],
        mpRegen: [650],
        skills: ['gattlingRailgun', 'heavyRailcannon', 'rocketStorm', 'airStrike'],
        armour: {physical: [50, 0], magic: [25, 0]},
        ai: `rng`,
    },
    redacted: { // boss
        enemyType: `redacted`,
        name: `[REDACTED]`, 
        rarity: EX,
        pfp: `assets/AnimeGirl51.jpeg`,
        hp: [975],
        mp: [1625],
        str: [2],
        int: [120],
        mpRegen: [200],
        agi: [125],
        skills: ['assaultRifle', 'swordDance', 'ultraHeavySlash'],
        armour: {physical: [75, 50], magic: [50, 50]},
        ai: `rng`,
    },
};
const gachaGameSummons = {
    bird: { // meat shield
        type: 'chicken',
        name: `Birb`,
        owner: `Henrietta`,
        rarity: N,
        pfp: `assets/bird.jpeg`,
        hp: 25,
        mp: 0,
        str: 1,
        int: 10,
        mpRegen: 0,
        agi: 200,
        skills: ['swoop', 'kamikaze'],
        armour: {physical: [0, 0], magic: [0, 0]},
    },
    rock: { // tanker
        type: 'object',
        name: `Rock`,
        owner: `Henrietta`,
        rarity: N,
        pfp: `assets/rocks.png`,
        hp: 100,
        mp: 0,
        str: 0,
        int: 0,
        mpRegen: 0,
        agi: 0,
        skills: ['exist'],
        armour: {physical: [10, 25], magic: [10, 25]},
    },
    chicken: { // meat shield
        type: 'chicken',
        name: `Lesser Chimkin`,
        owner: `π-thagoreas`,
        rarity: UC,
        pfp: `assets/summon2.jpeg`,
        hp: 40,
        mp: 10,
        str: 1,
        int: 10,
        mpRegen: 5,
        agi: 175,
        skills: ['peck', 'claw', 'charge'],
        armour: {physical: [0, 0], magic: [0, 0]},
    },
    rooster: { // support
        type: 'chicken',
        name: `Rooster`,
        owner: `π-thagoreas`,
        rarity: R,
        pfp: `assets/summon1.jpeg`,
        hp: 75,
        mp: 25,
        str: 1.5,
        int: 10,
        mpRegen: 10,
        skills: ['peck', 'claw', 'rallyingCall'],
        armour: {physical: [0, 0], magic: [0, 0]},
    },
    pheonix: { // tanker
        type: 'chicken',
        name: `Flaming Chimkin`,
        owner: `π-thagoreas`,
        rarity: SR,
        pfp: `assets/summon3.jpeg`,
        hp: 500,
        mp: 75,
        str: 2.5,
        int: 10,
        mpRegen: 15,
        skills: ['peck', 'claw', 'charge', 'minorInfernoBeam'],
        armour: {physical: [10, 25], magic: [10, 10]},
    },
    lowTierSkeleton: { // meat sheild
        type: 'undead',
        name: `Skeleton`,
        owner: `Shiori`,
        rarity: N,
        pfp: `assets/lesserSkeleton.jpeg`,
        hp: 75,
        mp: 0,
        str: 0.75,
        int: 10,
        mpRegen: 0,
        skills: ['slash', 'thrust', 'charge'],
        armour: {physical: [0, 0], magic: [0, 0]},
    },
    lesserDemon: { // dps
        type: 'demon',
        name: `Lesser Demon`,
        owner: `Shiori`,
        rarity: UC,
        pfp: `assets/lesserDemon.jpeg`,
        hp: 120,
        mp: 140,
        str: 1.25,
        int: 110,
        mpRegen: 40,
        skills: ['claw', 'minorInfernoBeam', 'bloodRain', 'demonicBlast'],
        armour: {physical: [5, 25], magic: [10, 25]},
    },

    // enemy summons
    scrapBotMelee: { // summoned bots have less hp and armour
        type: 'robot',
        enemyType: `scrapBotMelee`,
        name: `Scrap Bot`, 
        rarity: N,
        pfp: `assets/scrapBotMelee.jpeg`,
        hp: 45,
        mp: 0,
        str: 0.75,
        int: 100,
        mpRegen: 0,
        skills: ['claw', 'charge'], 
        armour: {physical: [0, 0], magic: [0, 0]},
        ai: `rng`,
    },
    scrapBotRanged: {
        type: 'robot',
        enemyType: `scrapBotRanged`,
        name: `Scrap Bot`, 
        rarity: N,
        pfp: `assets/scrapBotRanged.jpeg`,
        hp: 25,
        mp: 0,
        str: 0.75,
        int: 100,
        mpRegen: 0,
        skills: ['pistol', 'miniFlamethrower'], 
        armour: {physical: [0, 0], magic: [0, 0]},
        ai: `rng`,
    },
    securityDrone: {
        type: 'robot',
        enemyType: `securityDrone`,
        name: `Security Drone`, 
        rarity: R,
        pfp: `assets/securityDrone.jpeg`,
        hp: 175,
        mp: 150,
        str: 1,
        int: 100,
        mpRegen: 150,
        skills: ['laserBeam', 'chaingun', 'alarm', 'requestBackup'], 
        armour: {physical: [0, 0], magic: [0, 0]},
        ai: `rng`,
    },
    prototypeX27: {
        type: 'robot',
        enemyType: `macelinePrototype`,
        name: `Prototype X27`, 
        rarity: L,
        pfp: `assets/mech.jpeg`,
        hp: 2500,
        mp: 1000,
        str: 5,
        int: 100,
        mpRegen: 1000,
        agi: 125,
        skills: ['gattlingRailgun', 'heavyLaserBeam', 'infernoBeam', 'powerFist'],
        armour: {physical: [150, 75], magic: [90, 60]},
        ai: `rng`,
    },
};

const gachaGameCharacters = [rankN, rankUC, rankR, rankSR, rankE, rankL, rankM, rankG, rankEX];

for (let rank of gachaGameCharacters) { // Give everybody an empty inventory
    for (let character in rank) {
        rank[character].inventory = {
            hand: null,
            body: null
        }
    }
}

export {gachaGameCharacters, gachaGameEnemies, gachaGameSummons}; 