const goblinDen = {
    name: `Goblin Den`,
    outerBac: `assets/DungeonOuter1.jpeg`,
    innerBac: `assets/bronze.png`,
    waves: [
        { // 1
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 3,
                    location: `frontline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 2
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 4,
                    location: `frontline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 3
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 125, gold: 15},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 4
            type: `big`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 5,
                    location: `frontline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 4,
                    location: `backline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 2500, chance: 1}, {type: `gold`, quantity: 250, chance: 1}],
        },
        { // 5
            type: `normal`,
            enemies: [
                {
                    enemy: `goblinWarrior`,
                    lvl: 0,
                    quantity: 1,
                    location: `frontline`,
                    drops: {exp: 125, gold: 20},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 0,
                    quantity: 2,
                    location: `backline`,
                    drops: {exp: 125, gold: 15},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 6
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinWarrior`,
                    lvl: 0,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 125, gold: 20},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                {
                    enemy: `goblin`,
                    lvl: 0,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 100, gold: 10},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 7
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 1,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 110, gold: 12},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 125, gold: 15},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                {
                    enemy: `goblinWarrior`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 125, gold: 20},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 125, gold: 15},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 8
            type: `big`,
            enemies: [
                {
                    enemy: `goblinWarrior`,
                    lvl: 1,
                    quantity: 6,
                    location: `frontline`,
                    drops: {exp: 150, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 0,
                    quantity: 4,
                    location: `backline`,
                    drops: {exp: 125, gold: 15},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 2500, chance: 1}, {type: `gold`, quantity: 250, chance: 1}],
        },
        { // 9
            type: `normal`,
            enemies: [
                {
                    enemy: `goblinWarrior`,
                    lvl: 1,
                    quantity: 1,
                    location: `frontline`,
                    drops: {exp: 150, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblin`,
                    lvl: 1,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 110, gold: 12},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinWarrior`,
                    lvl: 1,
                    quantity: 1,
                    location: `frontline`,
                    drops: {exp: 150, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 10
            type: `normal`,
            enemies: [
                {
                    enemy: `goblinWarrior`,
                    lvl: 2,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 175, gold: 30},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblin`,
                    lvl: 2,
                    quantity: 3,
                    location: `backline`,
                    drops: {exp: 120, gold: 14},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 11
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 2,
                    quantity: 4,
                    location: `frontline`,
                    drops: {exp: 120, gold: 14},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 1,
                    quantity: 5,
                    location: `backline`,
                    drops: {exp: 145, gold: 18},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 12
            type: `big`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 2,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 120, gold: 14},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinWarrior`,
                    lvl: 2,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 175, gold: 30},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblin`,
                    lvl: 2,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 120, gold: 14},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 1,
                    quantity: 5,
                    location: `backline`,
                    drops: {exp: 145, gold: 18},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 2500, chance: 1}, {type: `gold`, quantity: 250, chance: 1}],
        },
        { // 13
            type: `normal`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 3,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 125, gold: 16},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
                {
                    enemy: `goblinWarrior`,
                    lvl: 2,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 175, gold: 30},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblin`,
                    lvl: 3,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 125, gold: 16},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 14
            type: `normal`,
            enemies: [
                {
                    enemy: `goblinWarrior`,
                    lvl: 2,
                    quantity: 1,
                    location: `frontline`,
                    drops: {exp: 175, gold: 30},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 2,
                    quantity: 5,
                    location: `backline`,
                    drops: {exp: 145, gold: 18},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 15
            type: `normal`,
            enemies: [
                {
                    enemy: `goblinWarrior`,
                    lvl: 2,
                    quantity: 2,
                    location: `frontline`,
                    drops: {exp: 175, gold: 30},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.2},
                },
                {
                    enemy: `goblinGuard`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 175, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.25},
                },
                {
                    enemy: `goblinArcher`,
                    lvl: 2,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 145, gold: 18},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                {
                    enemy: `goblinGuard`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 175, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.25},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // boss
            type: `boss`,
            enemies: [
                {
                    enemy: `goblin`,
                    lvl: 3,
                    quantity: 4,
                    location: `frontline`,
                    drops: {exp: 125, gold: 15},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.15},
                },
                {
                    enemy: `goblinGuard`,
                    lvl: 1,
                    quantity: 1,
                    location: `frontline`,
                    drops: {exp: 175, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.25},
                },
                {
                    enemy: `goblinLord`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 1000, gold: 500},
                    itemDrops: {item: `midGradeMagicStone`, chance: 0.75},
                },
                {
                    enemy: `goblinGuard`,
                    lvl: 1,
                    quantity: 1,
                    location: `frontline`,
                    drops: {exp: 175, gold: 25},
                    itemDrops: {item: `lowGradeMagicStone`, chance: 0.25},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 10000, chance: 1}, {type: `gold`, quantity: 1000, chance: 1}, {type: `item`, quantity: 1, chance: 1, item: `goblinWarHorn`}],
        },
    ],
    firstClearReward: [{type: `exp`, quantity: 25000, chance: 1}, {type: `gold`, quantity: 5000, chance: 1}, {type: `item`, quantity: 2, chance: 1, item: `goblinWarHorn`}],
};
const dragonPeaks = {
    name: `Dragon Peaks`,
    outerBac: `assets/DragonPeaks.jpeg`,
    innerBac: `assets/bronze.png`,
    waves: [
        { // 1
            type: `normal`,
            enemies: [
                {
                    enemy: `greenDragon`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 1000, gold: 100},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 2
            type: `normal`,
            enemies: [
                {
                    enemy: `greenDragon`,
                    lvl: 1,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 1000, gold: 100},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 3
            type: `normal`,
            enemies: [
                {
                    enemy: `crystalDragon`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 1500, gold: 150},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 4
            type: `big`,
            enemies: [
                {
                    enemy: `greenDragon`,
                    lvl: 0,
                    quantity: 3,
                    location: `backline`,
                    drops: {exp: 1000, gold: 100},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 2500, chance: 1}, {type: `gold`, quantity: 250, chance: 1}],
        },
        { // 5
            type: `normal`,
            enemies: [
                {
                    enemy: `electroDragon`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 2000, gold: 200},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.2},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 6
            type: `normal`,
            enemies: [
                {
                    enemy: `redDragon`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 2500, gold: 500},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.25},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 7
            type: `normal`,
            enemies: [
                {
                    enemy: `redDragonKing`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 5000, gold: 1000},
                    itemDrops: {item: `highGradeMagicStone`, chance: 0.5},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 1000, chance: 1}, {type: `gold`, quantity: 100, chance: 1}],
        },
        { // 8
            type: `big`,
            enemies: [
                {
                    enemy: `blackDragon`,
                    lvl: 0,
                    quantity: 1,
                    location: `backline`,
                    drops: {exp: 10000, gold: 1000},
                    itemDrops: {item: `highGradeMagicStone`, chance: 1},
                },
            ],
            clearRewards: [{type: `exp`, quantity: 2500, chance: 1}, {type: `gold`, quantity: 250, chance: 1}],
        },
    ],
    firstClearReward: [{type: `exp`, quantity: 25000, chance: 1}, {type: `gold`, quantity: 5000, chance: 1}, {type: `item`, quantity: 5, chance: 1, item: `dragonScale`}],
};

const gachaGameDungeons = [goblinDen, dragonPeaks];
export {gachaGameDungeons};