// Constants (catches spelling mistakes, the code will error if one of these is spelt wrong)
const N = 0;
const UC = 1;
const R = 2;
const SR = 3;
const E = 4;
const L = 5;
const G = 6;
const EX = 7;

const gold = 'gold';
const exp = 'exp';
const item = 'item';

const healthPots = [
    {
        id: `potHp1`,
        name: `Crude Health Potion`,
        displayName: `Health Potion`,
        description: `A concoction of various herbs that has some healing properties. The effects are weak, but it's better than nothing.`,
        rarity: N,
        pfp: `assets/pot2.jpeg`,
        useable: true,
        effects: [{effect: 'minorInstantHealth', chance: 100}],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 10,
        quantity: 0,
        stackSize: 999999999,
    },
    {
        id: `potHp2`,
        name: `Lesser Health Potion`,
        displayName: `Health Potion`,
        description: `A poorly crafted health potion crafted with low grade ingredients. It might just be enough for your troops to withstand an extra hit or two.`,
        rarity: UC,
        pfp: `assets/pot7.jpeg`,
        useable: true,
        effects: [{effect: 'lesserInstantHealth', chance: 100}],
        purchaceable: true,
        purchacePrice: 100,
        sellable: true,
        sellPrice: 25,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `potHp3`,
        name: `Mediocre Health Potion`,
        displayName: `Health Potion`,
        description: `The standard health potion sold in most high end stores. Very useful but expensive.`,
        rarity: R,
        pfp: `assets/pot8.jpeg`,
        useable: true,
        effects: [{effect: 'mediumInstantHealth', chance: 100}],
        purchaceable: true,
        purchacePrice: 400,
        sellable: true,
        sellPrice: 150,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `potHpRgn1`,
        name: `Potion of Regeneration`,
        displayName: `Regen Potion`,
        description: `An experimental healing potion designed by a master alchemist. The consumer will continuously regenerate health for a lengthy period of time.`,
        rarity: R,
        pfp: `assets/pot5.jpeg`,
        useable: true,
        effects: [{effect: 'lesserInstantHealth', chance: 100}, {effect: 'mediumHealOverTime', chance: 100}],
        purchaceable: true,
        purchacePrice: 300,
        sellable: true,
        sellPrice: 125,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `potHp4`,
        name: `Greater Health Potion`,
        displayName: `Health Potion`,
        description: `An incredible healing potion refined for years by a master alchemist. A single potion can heal even the most grevious injuries and replenishes lost mana.`,
        rarity: E,
        pfp: `assets/pot1.jpeg`,
        useable: true,
        effects: [{effect: 'greaterInstantHealth', chance: 100}, {effect: 'lesserInstantMana', chance: 100}],
        purchaceable: true,
        purchacePrice: 2500,
        sellable: true,
        sellPrice: 1000,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `potHp5`,
        name: `Superior Health Potion`,
        displayName: `Health Potion`,
        description: `A great alchemist didicated their entire lives to the refinement of this incredible healing potion. There are so few of them in existance that even the largest kingdoms only have a few stockpiled in their treasury.`,
        rarity: L,
        pfp: `assets/pot4.jpeg`,
        useable: true,
        effects: [{effect: 'superiorInstantHealth', chance: 100}, {effect: 'mediumHealOverTime', chance: 100}, {effect: 'mediumInstantMana', chance: 100}],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 10000,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `potHp6`,
        name: `Ascended Health Potion`,
        displayName: `Health Potion`,
        description: `A priceless relic from the age of the gods, this potion can bring even the strongest of heroes back to full health. It would surely be worth millions of gold.`,
        rarity: G,
        pfp: `assets/pot10.jpeg`,
        useable: true,
        effects: [{effect: 'ascendedInstantHealth', chance: 100}, {effect: 'ascendedHealOverTime', chance: 100}, {effect: 'mediumInstantMana', chance: 100}],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 1500000,
        quantity: 1,
        stackSize: 999999999,
    },
];
const stones = [
    {
        id: `stone1`,
        name: `Magic Stone`,
        displayName: `Crude Magic Stone`,
        description: `A rock that very faintly emits mana. It doesn't look very useful...`,
        rarity: N,
        pfp: `assets/blueRocks.png`,
        useable: false,
        effects: [],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 20,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `stone2`,
        name: `Magic Stone`,
        displayName: `Low Grade Magic Stone`,
        description: `A rock that faintly emits mana. Perhaps it could have some uses.`,
        rarity: UC,
        pfp: `assets/blueRocks.png`,
        useable: false,
        effects: [],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 100,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `stone3`,
        name: `Magic Stone`,
        displayName: `Medium Grade Magic Stone`,
        description: `A beautiful rock with mana swirling within it. This magic stone could be used to forge equipment or brew potions.`,
        rarity: R,
        pfp: `assets/blueRocks.png`,
        useable: false,
        effects: [],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 600,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `stone4`,
        name: `Magic Stone`,
        displayName: `High Grade Magic Stone`,
        description: `A beautiful rock surrounded by an aura of mana. It has many useful magical properties.`,
        rarity: E,
        pfp: `assets/blueRocks.png`,
        useable: false,
        effects: [],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 2000,
        quantity: 1,
        stackSize: 999999999,
    },
    {
        id: `stone5`,
        name: `Magic Stone`,
        displayName: `Perfected Magic Stone`,
        description: `A flawless magical stone containing immense mana.`,
        rarity: L,
        pfp: `assets/blueRocks.png`,
        useable: false,
        effects: [],
        purchaceable: false,
        purchacePrice: 0,
        sellable: true,
        sellPrice: 10000,
        quantity: 1,
        stackSize: 999999999,
    },
];

const gachaGameDrops = {
    dungeon: {
        normal: [{type: exp, quantity: 1000, chance: 100}, {type: gold, quantity: 100, chance: 100}],
        big: [{type: exp, quantity: 2500, chance: 100}, {type: gold, quantity: 250, chance: 100}],
        boss: [{type: exp, quantity: 10000, chance: 100}, {type: gold, quantity: 1000, chance: 100}],
    },
    clear: {
        goblinDen: [{type: item, quantity: 1, chance: 100, item: `goblinWarHorn`}],
        shadowCavern: [{type: exp, quantity: 5000, chance: 100}],
        dragonPeaks: [{type: exp, quantity: 25000, chance: 100}, {type: item, quantity: 5, chance: 100, item: `dragonScale`}],
        debugDungeon: [{type: exp, quantity: 100000, chance: 100}, {type: gold, quantity: 5000, chance: 100}],
        
        firstClear: [{type: exp, quantity: 50000, chance: 100}, {type: gold, quantity: 5000, chance: 100}],
    }, 
    enemy: {
        goblinGrunt: [{type: exp, quantity: 100, chance: 100}, {type: item, quantity: 1, chance: 25, item: 'stone1'}],
        goblinArcher: [{type: exp, quantity: 150, chance: 100}, {type: item, quantity: 1, chance: 50, item: 'stone1'}],
        goblinWarrior: [{type: exp, quantity: 200, chance: 100}, {type: item, quantity: 1, chance: 75, item: 'stone1'}],
        goblinGuard: [{type: exp, quantity: 250, chance: 100}, {type: item, quantity: 1, chance: 75, item: 'stone1'}],
        goblinBoss: [{type: exp, quantity: 1000, chance: 100}, {type: item, quantity: 1, chance: 100, item: 'stone2'}],

        dragonGreen: [{type: exp, quantity: 1500, chance: 100}, {type: item, quantity: 1, chance: 25, item: 'stone4'}],
        dragonRainbow: [{type: exp, quantity: 2500, chance: 100}, {type: item, quantity: 1, chance: 50, item: 'stone4'}],
        dragonBlue: [{type: exp, quantity: 5000, chance: 100}, {type: item, quantity: 1, chance: 90, item: 'stone4'}],
        dragonRed: [{type: exp, quantity: 7500, chance: 100}, {type: item, quantity: 1, chance: 75, item: 'stone4'}],
        dragonBlack: [{type: exp, quantity: 12500, chance: 100}, {type: item, quantity: 1, chance: 50, item: 'stone5'}],
        dragonRedBig: [{type: exp, quantity: 12500, chance: 100}, {type: item, quantity: 1, chance: 50, item: 'stone5'}],

        shadowBat: [{type: exp, quantity: 250, chance: 100}, {type: item, quantity: 1, chance: 25, item: 'stone1'}],
        spider: [{type: exp, quantity: 300, chance: 100}, {type: item, quantity: 1, chance: 50, item: 'stone1'}],
        scorpion: [{type: exp, quantity: 500, chance: 100}, {type: item, quantity: 1, chance: 40, item: 'stone2'}],
        snake: [{type: exp, quantity: 500, chance: 100}, {type: item, quantity: 1, chance: 60, item: 'stone2'}],

        chicken: [{type: exp, quantity: 25000, chance: 100}, {type: item, quantity: 1, chance: 25, item: 'stone5'}],
        chickenStrong: [{type: exp, quantity: 75000, chance: 100}, {type: item, quantity: 1, chance: 50, item: 'stone5'}],
        chickenVeryStrong: [{type: exp, quantity: 200000, chance: 100}, {type: item, quantity: 1, chance: 75, item: 'stone5'}],
    },
};

const gachaGameItems = [].concat(healthPots, stones);

export {gachaGameItems, gachaGameDrops};