// Obsolete and no longer used
const oldSkills = {
    skillsOld: {
        positronRay: {
            name: `Positron Ray`,
            desc: `[attacker] launches a concentrated ray of positrons at the targeted enemy.`,
            attackType: `beam`,
            type: piercing,
            targeting: single,
            dmg: 1,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 10},
            accuracy: 90,
            attacks: 10,
        },
        peck: {
            name: `Peck`,
            desc: `[attacker] pecks the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 20,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 90,
            attacks: 1,
        },
        scratch: {
            name: `Scratch`,
            desc: `[attacker] scratches the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: multi,
            dmg: 5,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 90,
            attacks: 4,
        },
        soulHarvest: {
            name: `Soul Harvest`,
            desc: `[attacker] reaps the tageted enemy's soul with [pronoun] sythe.`,
            attackType: `physical`,
            type: piercing,
            targeting: single,
            dmg: 1000,
            multiplier: str,
            effects: [{id: 'hot', lvl: 975, duration: 1}],
            cost: {hp: 0, mp: 1400},
            accuracy: 500,
            attacks: 1,
        },
        slash: {
            name: `Slash`,
            desc: `[attacker] shashes at the targeted enemy, inflicing damage (hopefully).`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 15,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 90,
            attacks: 3,
        },
        machinegun: {
            name: `Assault Rifle`,
            desc: `[attacker] unloads a full magazine into the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: multi,
            dmg: 25,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 100,
            attacks: 30,
        },
        millionSlashes: {
            name: `Million Slashes`,
            desc: `[attacker] swings [pronoun] blade at extreme speeds hitting the targeted enemy countless times.`,
            attackType: `physical`,
            type: physical,
            targeting: multi,
            dmg: 16,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 100,
            attacks: 10,
        },
        sevenfoldSlashOfLight: {
            name: `Sevenfold Slash of Light`,
            desc: `[attacker] channels mana into [pronoun] sword and unleashes 7 consecutive slashes at the targeted enemy.`,
            attackType: `physical`,
            type: normal,
            targeting: multi,
            dmg: 22,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 90},
            accuracy: 200,
            attacks: 7,
        },
        auraSlash: {
            name: `Aura Slash`,
            desc: `[attacker] launches [pronoun] sword aura at the targeted enemy.`,
            attackType: `physical`,
            type: normal,
            targeting: single,
            dmg: 225,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 300},
            accuracy: 100,
            attacks: 1,
        },
        thrust: {
            name: `Sword Thrust`,
            desc: `[attacker] impales the targeted enemy with [pronoun] sword.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 60,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 75,
            attacks: 1,
        },
        superiorThrust: {
            name: `Sword Thrust`,
            desc: `[attacker] enhances [pronoun] sword with aura and impales the targeted enemy.`,
            attackType: `physical`,
            type: normal,
            targeting: single,
            dmg: 90,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 20},
            accuracy: 100,
            attacks: 1,
        },
        godslayerSlash: {
            name: `God Slaying Slash`,
            desc: `[attacker] charges [pronoun] sword with a vast amount of energy, releasing a slash that cuts through even reality itself.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 1250,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 800},
            accuracy: Infinity,
            attacks: 1,
        },
        overheadStrike: {
            name: `Overhead Strike`,
            desc: `[attacker] leaps into the air and strikes at the targeted enemy from above.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 75,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 50,
            attacks: 1,
        },
        superiorOverheadStrike: {
            name: `Overhead Strike`,
            desc: `[attacker] leaps into the air and strikes at the targeted enemy from above.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 150,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 200,
            attacks: 1,
        },
        extremeOverheadStrike: {
            name: `Overhead Strike`,
            desc: `[attacker] leaps into the air and strikes at the targeted enemy from above.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 400,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 250},
            accuracy: 200,
            attacks: 1,
        },
        sparkleSlash: {
            name: `Sparkle Slash`,
            desc: `[attacker]'s special attack that [pronoun] spent years developing. It is rather flashy and powerful...`,
            attackType: `physical`,
            type: normal,
            targeting: single,
            dmg: 40,
            multiplier: str,
            effects: [],
            cost: {hp: 40, mp: 100},
            accuracy: 70,
            attacks: 5,
        },
        wildSwing: {
            name: `Wild Swings`,
            desc: `[attacker] wildly swings [pronoun] sword at the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 36,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 60,
            attacks: 2,
        },
        heavyStrike: {
            name: `Heavy Strike`,
            desc: `[attacker] infises mana into [pronoun] sword and unleashes a powerful slash at the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 80,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 10},
            accuracy: 100,
            attacks: 1,
        },
        raiseGuard: {
            name: `Raise Guard`,
            desc: `[attacker] raises [pronoun] guard, reducing damage from all attacks in the next round.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [15, 5], duration: 1}],
            cost: {hp: 0, mp: 5},
            accuracy: Infinity,
            attacks: 1,
            selfOnly: true,
        },
        extremeRaiseGuard: {
            name: `Raise Guard`,
            desc: `[attacker] raises [pronoun] guard, greatly reducing damage in the next 2 rounds.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [100, 10], duration: 2}, {id: 'mdef', lvl: [100, 25], duration: 2}],
            cost: {hp: 0, mp: 300},
            accuracy: Infinity,
            attacks: 1,
            selfOnly: true,
        },
        focusAura: {
            name: `Focus Aura`,
            desc: `[attacker] gathers the aura within [pronoun], drasticly increasing all stats for 3 rounds.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [100, 75], duration: 3}, {id: 'mdef', lvl: [0, 75], duration: 3}, {id: 'atk', lvl: 1, duration: 5}, {id: 'mreg', lvl: 50, duration: 5}],
            cost: {hp: 0, mp: 375},
            accuracy: Infinity,
            attacks: 1,
            selfOnly: true,
        },
        cower: {
            name: `Cower in Fear`,
            desc: `[attacker] cowers in fear, channeling mana into [pronoun] armour to reist more damage.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [15, 10], duration: 1}],
            cost: {hp: 0, mp: 25},
            accuracy: Infinity,
            attacks: 1,
        },
        superchargeArmour: {
            name: `Strengthen Armour`,
            desc: `[attacker] channeling mana into [pronoun] armour to reist more damage for 5 rounds.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [50, 10], duration: 5}],
            cost: {hp: 0, mp: 25},
            accuracy: Infinity,
            attacks: 1,
            selfOnly: true,
        },
        counterAttack: {
            name: `Perpare Counter Attack`,
            desc: `[attacker] reduces all damage taken in the next round, and counteratacks with 150% power against the next enemy to attack [pronoun] at melee range.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [0, 5], duration: 1}, {id: 'counter', lvl: 1.5, duration: 1}],
            cost: {hp: 0, mp: 0},
            accuracy: Infinity,
            attacks: 1,
            selfOnly: true,
        },
        superiorCounterAttack: {
            name: `Perpare Counter Attack`,
            desc: `[attacker] reduces all damage taken in the next 3 rounds, and counteratacks with 150% power against the next 3 enemy to attack [pronoun] at melee range.`,
            attackType: `buffDefence`,
            type: normal,
            targeting: selfOnly,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [50, 10], duration: 3}, {id: 'counter', lvl: 1.5, duration: 3}],
            cost: {hp: 0, mp: 0},
            accuracy: Infinity,
            attacks: 1,
            selfOnly: true,
        },
        swordCharge: {
            name: `Sword Charge`,
            desc: `[attacker] channels mana into [pronoun] sword and charges the targeted enemy inflicting great damage, but taking some damage as well.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 125,
            multiplier: str,
            effects: [],
            cost: {hp: 10, mp: 15},
            accuracy: 90,
            attacks: 1,
        },
        wildCharge: {
            name: `Wild Charge`,
            desc: `[attacker] charges the targeted enemy while flailing [pronoun] sword wildly inflicting significant damage to all parties.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 18,
            multiplier: str,
            effects: [],
            cost: {hp: 30, mp: 15},
            accuracy: 50,
            attacks: 6,
        },
        swordDance: {
            name: `Sword Dance`,
            desc: `[attacker] sends a flury of rapid slashes and stabs at the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: multi,
            dmg: 35,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 425},
            accuracy: 150,
            attacks: 45,
        },
        savageTornado: {
            name: `Savage Tornado`,
            desc: `[attacker] spins in a circle slashing at the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: multi,
            dmg: 85,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 200},
            accuracy: 200,
            attacks: 5,
        },
        punch: {
            name: `Punch`,
            desc: `[attacker] punches the targeted enemy.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 15,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 100,
            attacks: 1,
        },
        bodyslam: {
            name: `Bodyslam`,
            desc: `[attacker] bodyslams the targeted enemy, dealing damage to both of them.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 50,
            multiplier: str,
            effects: [],
            cost: {hp: 10, mp: 0},
            accuracy: 90,
            attacks: 1,
        },
        slap: {
            name: `Slap`,
            desc: `[attacker] slaps the targeted enemy inflicting a little damage.`,
            attackType: `physical`,
            type: physical,
            targeting: single,
            dmg: 10,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 100,
            attacks: 1,
        },
        stare: {
            name: `Prevy Stare`,
            desc: `[attacker] stares at the targeted enemy like a pervert. Its super effective against females.`,
            attackType: `scan`,
            type: normal,
            targeting: single,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 15},
            accuracy: 60,
            exec: `
            if (enemy.gender == female) {
                attack.dmg = 99999,
            }
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `question.png`,
                    desc: `effects unknown`,
                },
            ],
        },
        roosterRallyingCall: {
            name: `Rallying Call`,
            desc: `[attacker] motivates all allied chickens, increasing their defense and attack power for 3 rounds. Gives +25% attack damage, 10 physical negation and 10% physical damage resistance.`,
            attackType: `buff`,
            type: normal,
            targeting: aoe,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: Infinity,
            exec: `
            for (let i = 0; i < game.gamestate.player.team.length; i++) {
                if (game.gamestate.player.team[i].name == 'Chicken') {
                    game.gamestate.player.team[i].effects.push({id: 'def', lvl: [10, 10], duration: 3}, {id: 'atk', lvl: 0.25, duration: 3});
                }
            }
            `,
            attacks: 1,
        },
        rallyingCall: {
            name: `Rallying Call`,
            desc: `[attacker] motivates all allies, increasing their defense and attack power for 3 rounds.`,
            attackType: `buff`,
            type: normal,
            targeting: aoe,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 225},
            accuracy: Infinity,
            exec: `
            for (let i = 0; i < game.gamestate.player.team.length; i++) {
                game.gamestate.player.team[i].effects.push({id: 'def', lvl: [10, 10], duration: 3}, {id: 'atk', lvl: 0.25, duration: 3});
            }
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `clock.png`,
                    desc: `lasts 3 rounds`,
                },
                {
                    icon: `shield.png`,
                    desc: `10 physical negation to all allies`,
                },
                {
                    icon: `shield.png`,
                    desc: `10% physical resist to all allies`,
                },
                {
                    icon: `lightning.png`,
                    desc: `25% extra attack damage to all allies`,
                },
            ],
        },
        lecture: {
            name: `Lecture`,
            desc: `[attacker] enlightens all allies on the weaknesses of their enemies, increasing their attack power for 3 rounds.`,
            attackType: `buff`,
            type: normal,
            targeting: aoe,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 100},
            accuracy: Infinity,
            exec: `
            for (let i = 0; i < game.gamestate.player.team.length; i++) {
                game.gamestate.player.team[i].effects.push({id: 'atk', lvl: 0.25, duration: 3});
            }
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `clock.png`,
                    desc: `lasts 3 rounds`,
                },
                {
                    icon: `lightning.png`,
                    desc: `25% extra attack damage to all allies`,
                },
            ],
        },
        analysis: {
            name: `Analyse Enemy`,
            desc: `[attacker] analyses the targeted enemy, revealing their weaknesses.`,
            attackType: `buff`,
            type: normal,
            targeting: single,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'def', lvl: [0, -25], duration: 5}, {id: 'mdef', lvl: [0, -25], duration: 5}],
            cost: {hp: 0, mp: 50},
            accuracy: Infinity,
            attacks: 1,
            extraStats: [
                {
                    icon: `clock.png`,
                    desc: `lasts 5 rounds`,
                },
                {
                    icon: `explode.png`,
                    desc: `take 25% more damage from all attacks`,
                },
            ],
            preventDefault: true,
        },
        gravityBind: {
            name: `Gravity Bind`,
            desc: `[attacker] weakens the targeted enemy by increasing the gravitational field strength around them.`,
            attackType: `buff`,
            type: normal,
            targeting: single,
            dmg: 0,
            multiplier: none,
            effects: [{id: 'atk', lvl: -0.5, duration: 1}],
            cost: {hp: 0, mp: 125},
            accuracy: Infinity,
            attacks: 1,
            extraStats: [
                {
                    icon: `clock.png`,
                    desc: `lasts 1 rounds`,
                },
                {
                    icon: `lightning.png`,
                    desc: `deal 50% less damage`,
                },
            ],
            preventDefault: true,
        },
        brag: {
            name: `Brag`,
            desc: `[attacker] brags about [pronoun] accomplishments, irritating the targeted enemy.`,
            attackType: `sound`,
            type: piercing,
            targeting: single,
            dmg: 0,
            multiplier: int,
            effects: [{id: 'dot', lvl: 10, duration: 3}],
            cost: {hp: 0, mp: 5},
            accuracy: 100,
            attacks: 1,
        },
        insult: {
            name: `Insult`,
            desc: `[attacker] insults the targeted enemy, calling them a spedlord. The targeted enemy will take more damage but hit harder`,
            attackType: `sound`,
            type: piercing,
            targeting: single,
            dmg: 10,
            multiplier: int,
            effects: [{id: 'def', lvl: [-10, -25], duration: 5}, {id: 'atk', lvl: 0.5, duration: 5}],
            cost: {hp: 0, mp: 5},
            accuracy: 100,
            attacks: 1,
        },
        lesserHeal: {
            name: `Lesser Healing`,
            desc: `[attacker] heals the targeted ally.`,
            attackType: `heal`,
            type: magic,
            targeting: single,
            dmg: -20,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 25},
            accuracy: 500,
            attacks: 1,
        },
        lesserAreaHeal: {
            name: `Lesser Area Healing`,
            desc: `[attacker] heals all allies, focusing on the targeted ally.`,
            attackType: `areaHeal`,
            type: magic,
            targeting: aoe,
            dmg: -10,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 60},
            accuracy: 500,
            exec: `
            for (let i = 0; i < game.gamestate.player.team.length; i++) {
                game.gamestate.player.team[i].hp += 10;
            }
            `,
            extraStats: {
                icon: `greenCross.png`,
                desc: `10 heal to all allies`,
            },
            attacks: 1,
        },
        mediumHeal: {
            name: `Medium Healing`,
            desc: `[attacker] heals the targeted ally.`,
            attackType: `heal`,
            type: magic,
            targeting: single,
            dmg: -35,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 40},
            accuracy: 500,
            attacks: 1,
        },
        greaterHeal: {
            name: `Greater Healing`,
            desc: `[attacker] heals the targeted ally.`,
            attackType: `heal`,
            type: magic,
            targeting: single,
            dmg: -80,
            multiplier: int,
            effects: [{id: 'hot', lvl: 5, duration: 2}],
            cost: {hp: 0, mp: 90},
            accuracy: 500,
            attacks: 1,
        },
        shadowLance: {
            name: `Shadow Lance`,
            desc: `[attacker] launches a shadow lance constructed from mana at the targeted enemy. It can penetrate through barriers and armour.`,
            attackType: `darkMagic`,
            type: piercing,
            targeting: single,
            dmg: 40,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 45},
            accuracy: 100,
            attacks: 1,
        },
        arcaneBlast: {
            name: `Arcane Blast`,
            desc: `[attacker] fires a concentrated blast of mana at the targeted enemy.`,
            attackType: `magic`,
            type: magic,
            targeting: single,
            dmg: 175,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 200},
            accuracy: 100,
            attacks: 1,
        },
        darkBlast: {
            name: `Dark Blast`,
            desc: `[attacker] fires a concentrated blast of dark elemental mana at the targeted enemy.`,
            attackType: `darkMagic`,
            type: magic,
            targeting: single,
            dmg: 90,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 90},
            accuracy: 100,
            attacks: 1,
        },
        shadowVeil: {
            name: `Shadow Veil`,
            desc: `[attacker] surrounds the targeted ally in an anti magic barrier.`,
            attackType: `darkBarrier`,
            type: magic,
            targeting: single,
            dmg: 0,
            multiplier: int,
            effects: [{id: 'barrier', lvl: 750, duration: 25, type: magic}],
            cost: {hp: 0, mp: 300},
            accuracy: 1000,
            attacks: 1,
        },
        fireball: {
            name: `Fireball`,
            desc: `[attacker] launches a fireball at the targeted enemy.`,
            attackType: `fireMagic`,
            type: magic,
            targeting: single,
            dmg: 25,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 20},
            accuracy: 100,
            attacks: 1,
        },
        firestorm: {
            name: `Firestorm`,
            desc: `[attacker] unleashes a storm of fire at the targeted enemy, dealing splash damage to all enemies.`,
            attackType: `fireAOE`,
            type: magic,
            targeting: aoe,
            dmg: 10,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 100},
            accuracy: Infinity,
            exec: `
            for (let i = 0; i < game.gamestate.enemies.length; i++) {
                game.gamestate.enemies.hp -= 20;
            }
            `,
            attacks: 1,
            extraStats: [{
                icon: `lightning.png`,
                desc: `20 damage to all enemies`,
            }],
        },
        fireLance: {
            name: `Fire Lance`,
            desc: `[attacker] fires a clance of fire at the targeted enemy.`,
            attackType: `fireMagic`,
            type: magic,
            targeting: single,
            dmg: 40,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 45},
            accuracy: 140,
            attacks: 1,
        },
        fireArrows: {
            name: `Fire Arrows`,
            desc: `[attacker] summons and fires arrows of fire at the targeted enemy.`,
            attackType: `fireMagic`,
            type: magic,
            targeting: multi,
            dmg: 10,
            multiplier: int,
            effects: [],
            cost: {hp: 0, mp: 50},
            accuracy: 75,
            attacks: 5,
        },
        fragGrenade: {
            name: `Frag Grenade`,
            desc: `[attacker] throws a frag grenade at the targeted enemy.`,
            attackType: `fireAOE`,
            type: physical,
            targeting: aoe,
            dmg: 300,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: Infinity,
            exec: `
            for (let i = 0; i < game.gamestate.enemies.length; i++) {
                game.gamestate.enemies.hp -= 250;
            }
            `,
            attacks: 1,
            extraStats: [{
                icon: `lightning.png`,
                desc: `250 damage to all enemies`,
            }],
        },
        summonPotato: {
            name: `Summon Potato`,
            desc: `[attacker] summons a potato. IDK what it does.`,
            attackType: `summon`,
            type: physical,
            targeting: summon,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 50},
            accuracy: Infinity,
            exec: `
            // summon potato here
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `box.png`,
                    desc: `summon 1 potato`,
                },
                {
                    icon: `redCross.png`,
                    desc: `10 chicken hp`,
                },
            ],
            preventDefault: true,
        },
        summonChicken: {
            name: `Summon Chicken`,
            desc: `[attacker] summons a chicken to help fight.`,
            attackType: `summon`,
            type: physical,
            targeting: summon,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 60},
            accuracy: Infinity,
            exec: `
            // summon chickens here
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `box.png`,
                    desc: `summon 1 chicken`,
                },
                {
                    icon: `redCross.png`,
                    desc: `40 chicken hp`,
                },
                {
                    icon: `lightning.png`,
                    desc: `20 chicken attack damage`,
                },
            ],
            preventDefault: true,
        },
        summonChickenFlock: {
            name: `Summon Flock`,
            desc: `[attacker] summons a flock of chickens to help fight.`,
            attackType: `summon`,
            type: physical,
            targeting: summon,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 400},
            accuracy: Infinity,
            exec: `
            // summon chickens here
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `box.png`,
                    desc: `summon 5 chicken`,
                },
                {
                    icon: `redCross.png`,
                    desc: `40 chicken hp`,
                },
                {
                    icon: `lightning.png`,
                    desc: `20 chicken attack damage`,
                },
            ],
            preventDefault: true,
        },
        summonRooster: {
            name: `Summon Rooster`,
            desc: `[attacker] summons a rooster to help fight.`,
            attackType: `summon`,
            type: physical,
            targeting: summon,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 100},
            accuracy: Infinity,
            exec: `
            // summon chickens here
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `box.png`,
                    desc: `summon 1 chicken`,
                },
                {
                    icon: `redCross.png`,
                    desc: `60 chicken hp`,
                },
                {
                    icon: `lightning.png`,
                    desc: `30 chicken attack damage`,
                },
            ],
            preventDefault: true,
        },
        summonPheonix: {
            name: `Summon Pheonix`,
            desc: `[attacker] summons a Pheonix, the penultimate form of the chicken, to help fight.`,
            attackType: `summon`,
            type: physical,
            targeting: summon,
            dmg: 0,
            multiplier: none,
            effects: [],
            cost: {hp: 0, mp: 450},
            accuracy: Infinity,
            exec: `
            // summon pheonix here
            `,
            attacks: 1,
            extraStats: [
                {
                    icon: `box.png`,
                    desc: `summon 1 pheonix`,
                },
                {
                    icon: `redCross.png`,
                    desc: `500 pheonix hp`,
                },
                {
                    icon: `lightning.png`,
                    desc: `100 pheonix attack damage`,
                },
            ],
            preventDefault: true,
        },
    },
    enemySkillsOld: {
        hit: {
            attackType: `physical`,
            type: physical,
            dmg: 20,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 90,
            attacks: 1,
        },
        rapidHit: {
            attackType: `physical`,
            type: physical,
            dmg: 12,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 80,
            attacks: 3,
        },
        smash: {
            attackType: `physical`,
            type: physical,
            dmg: 35,
            multiplier: str,
            effects: [],
            cost: {hp: 10, mp: 0},
            accuracy: 70,
            attacks: 1,
        },
        crossbow: {
            attackType: `arrow`,
            type: physical,
            dmg: 25,
            multiplier: str,
            effects: [],
            cost: {hp: 0, mp: 0},
            accuracy: 90,
            attacks: 1,
        },
    },
}